In [1]:
import pandas as pd

df_nodal_hierarchy = pd.read_csv('C:\\Users\\akarmaka\\Documents\\GitHub\\ReEDS-2.0\\inputs\\hierarchy_rts_nodal.csv', header=0)

df_reeds_gens = pd.read_csv('C:\\Users\\akarmaka\\Documents\\GitHub\\ReEDS-2.0\\inputs\\capacitydata\\ReEDS_generator_database_final_RTS-GMLC_withRTPV.csv', header=0)

df_reeds_gens
#df_p1_census = pd.read_csv('co-est2021-alldata.csv', header=0, usecols=['STNAME','CTYNAME','POPESTIMATE2021','STATE','COUNTY'], nrows=3195, encoding='latin-1')
#print(df_p1_census)

#df_p1_counties = pd.read_excel('county_reeds_corrected0310.xlsx', header=0, usecols=['NAME','STATE_NAME','FIPS','PCA_REG'])
#print(df_p1_counties)

#df_heirarchy_others = pd.read_csv('hierarchy_fips.csv', header = 0, usecols = ['FIPS','BA','nercr','transreg','cendiv','st', 'interconnect','country','usda','aggreg'])
#df_heirarchy_others = pd.read_csv('Reeds_SpatialFlex\\fprice\\hierarchy_bokeh.csv', header = 0) #, usecols = ['FIPS','BA','nercr','transreg','cendiv','st', 'interconnect','country','usda','aggreg'])

#df_heirarchy_others

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,tech,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,ctt,Nuke80RetireYear,StartYear,IsExistUnit,wst,resource_region,TC_WIN,coolingwatertech,RetireYear,sc_point_gid
0,101_CT_1,101,1,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,n,2050,2012,True,fsa,328,20.0,o-g-s_n_fsa,2042,0
1,101_CT_2,101,2,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,n,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,1
2,101_STEAM_3,101,3,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,n,2050,2012,True,fsa,328,76.0,coalolduns_n_fsa,2042,2
3,101_STEAM_4,101,4,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,n,2050,2009,True,fsa,328,76.0,coalolduns_n_fsa,2039,3
4,102_CT_1,102,1,U20,CT,o-g-s,Oil,8.0,4.88,1.0467,...,n,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,309_WIND_1,309,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2012,True,fsa,342,148.3,wind-ons_n_fsa,2042,153
151,317_WIND_1,317,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,342,799.1,wind-ons_n_fsa,2039,154
152,303_WIND_1,303,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,342,847.0,wind-ons_n_fsa,2039,155
153,122_WIND_1,122,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,328,713.5,wind-ons_n_fsa,2039,156
154,313_STORAGE_1,313,1,STORAGE,STORAGE,battery_4,Storage,0.0,0.00,1.0000,...,n,2050,2012,True,fsa,342,50.0,battery_4_n_fsa,2042,157

In [4]:
df_reeds_gens['Bus ID'] = df_reeds_gens['Bus ID'].astype(str)

df_reeds_gens['reeds_ba'] = "b" + df_reeds_gens['Bus ID']
df_reeds_gens

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,tech,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,ctt,Nuke80RetireYear,StartYear,IsExistUnit,wst,resource_region,TC_WIN,coolingwatertech,RetireYear,sc_point_gid
0,101_CT_1,101,1,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,n,2050,2012,True,fsa,328,20.0,o-g-s_n_fsa,2042,0
1,101_CT_2,101,2,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,n,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,1
2,101_STEAM_3,101,3,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,n,2050,2012,True,fsa,328,76.0,coalolduns_n_fsa,2042,2
3,101_STEAM_4,101,4,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,n,2050,2009,True,fsa,328,76.0,coalolduns_n_fsa,2039,3
4,102_CT_1,102,1,U20,CT,o-g-s,Oil,8.0,4.88,1.0467,...,n,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,309_WIND_1,309,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2012,True,fsa,342,148.3,wind-ons_n_fsa,2042,153
151,317_WIND_1,317,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,342,799.1,wind-ons_n_fsa,2039,154
152,303_WIND_1,303,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,342,847.0,wind-ons_n_fsa,2039,155
153,122_WIND_1,122,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,n,2050,2009,True,fsa,328,713.5,wind-ons_n_fsa,2039,156
154,313_STORAGE_1,313,1,STORAGE,STORAGE,battery_4,Storage,0.0,0.00,1.0000,...,n,2050,2012,True,fsa,342,50.0,battery_4_n_fsa,2042,157

In [5]:
#left_on = reeds_ba before switching column name; updated should be reeds_nodal
df_hierarchy_nodal_gens = pd.merge(df_reeds_gens, df_nodal_hierarchy, left_on=['reeds_ba'], right_on=['*Nodal'], how='inner')
df_hierarchy_nodal_gens

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,tech,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,FIPS,BA,nercr,transreg,st,interconnect,country,usda,aggreg,county_name
0,101_CT_1,101,1,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,p04012,p28,WECC_SRSG,WestConnect,AZ,western,USA,mountain,AZ,La Paz
1,101_CT_2,101,2,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,p04012,p28,WECC_SRSG,WestConnect,AZ,western,USA,mountain,AZ,La Paz
2,101_STEAM_3,101,3,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,p04012,p28,WECC_SRSG,WestConnect,AZ,western,USA,mountain,AZ,La Paz
3,101_STEAM_4,101,4,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,p04012,p28,WECC_SRSG,WestConnect,AZ,western,USA,mountain,AZ,La Paz
4,101_PV_1,101,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,p04012,p28,WECC_SRSG,WestConnect,AZ,western,USA,mountain,AZ,La Paz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,119_PV_1,119,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,p06065,p10,WECC_CA,CAISO,CA,western,USA,pacific,CA_S_CAISO,Riverside
151,308_RTPV_1,308,1,RTPV,RTPV,distpv,Solar,0.0,0.00,1.0000,...,p06037,p10,WECC_CA,CAISO,CA,western,USA,pacific,CA_S_CAISO,Los Angeles
152,309_WIND_1,309,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,p06037,p10,WECC_CA,CAISO,CA,western,USA,pacific,CA_S_CAISO,Los Angeles
153,317_WIND_1,317,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,p06071,p10,WECC_CA,CAISO,CA,western,USA,pacific,CA_S_CAISO,San Bernardino
154,303_WIND_1,303,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,p06029,p10,WECC_CA,CAISO,CA,western,USA,pacific,CA_S_CAISO,Kern

In [6]:
df_hierarchy_nodal_gens.drop(['*Nodal', 'FIPS', 'nercr', 'transreg','st', 'interconnect', 'country', 'usda', 'aggreg', 'county_name'], axis=1, inplace=True)
df_hierarchy_nodal_gens

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,tech,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Nuke80RetireYear,StartYear,IsExistUnit,wst,resource_region,TC_WIN,coolingwatertech,RetireYear,sc_point_gid,BA
0,101_CT_1,101,1,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,2050,2012,True,fsa,328,20.0,o-g-s_n_fsa,2042,0,p28
1,101_CT_2,101,2,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,1,p28
2,101_STEAM_3,101,3,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,2050,2012,True,fsa,328,76.0,coalolduns_n_fsa,2042,2,p28
3,101_STEAM_4,101,4,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,2050,2009,True,fsa,328,76.0,coalolduns_n_fsa,2039,3,p28
4,101_PV_1,101,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,2050,2009,True,fsa,328,25.9,upv_n_fsa,2039,113,p28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,119_PV_1,119,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,2050,2009,True,fsa,328,66.6,upv_n_fsa,2039,121,p10
151,308_RTPV_1,308,1,RTPV,RTPV,distpv,Solar,0.0,0.00,1.0000,...,2050,2012,True,fsa,342,100.9,distpv_n_fsa,2042,122,p10
152,309_WIND_1,309,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2012,True,fsa,342,148.3,wind-ons_n_fsa,2042,153,p10
153,317_WIND_1,317,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2009,True,fsa,342,799.1,wind-ons_n_fsa,2039,154,p10
154,303_WIND_1,303,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2009,True,fsa,342,847.0,wind-ons_n_fsa,2039,155,p10

In [7]:
df_hierarchy_nodal_gens.rename(columns = {'reeds_ba':'reeds_nodal', 'BA':'reeds_ba'}, inplace = True)
df_hierarchy_nodal_gens

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,tech,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Nuke80RetireYear,StartYear,IsExistUnit,wst,resource_region,TC_WIN,coolingwatertech,RetireYear,sc_point_gid,reeds_ba
0,101_CT_1,101,1,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,2050,2012,True,fsa,328,20.0,o-g-s_n_fsa,2042,0,p28
1,101_CT_2,101,2,U20,CT,o-g-s,Oil,8.0,4.96,1.0468,...,2050,2009,True,fsa,328,20.0,o-g-s_n_fsa,2039,1,p28
2,101_STEAM_3,101,3,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,2050,2012,True,fsa,328,76.0,coalolduns_n_fsa,2042,2,p28
3,101_STEAM_4,101,4,U76,STEAM,coalolduns,Coal,76.0,0.14,1.0468,...,2050,2009,True,fsa,328,76.0,coalolduns_n_fsa,2039,3,p28
4,101_PV_1,101,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,2050,2009,True,fsa,328,25.9,upv_n_fsa,2039,113,p28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,119_PV_1,119,1,PV,PV,upv,Solar,0.0,0.00,1.0000,...,2050,2009,True,fsa,328,66.6,upv_n_fsa,2039,121,p10
151,308_RTPV_1,308,1,RTPV,RTPV,distpv,Solar,0.0,0.00,1.0000,...,2050,2012,True,fsa,342,100.9,distpv_n_fsa,2042,122,p10
152,309_WIND_1,309,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2012,True,fsa,342,148.3,wind-ons_n_fsa,2042,153,p10
153,317_WIND_1,317,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2009,True,fsa,342,799.1,wind-ons_n_fsa,2039,154,p10
154,303_WIND_1,303,1,WIND,WIND,wind-ons,Wind,0.0,0.00,1.0000,...,2050,2009,True,fsa,342,847.0,wind-ons_n_fsa,2039,155,p10

In [8]:
# Write dataframe to csv file (UNCOMPRESSED)
df_hierarchy_nodal_gens.to_csv('C:\\Users\\akarmaka\\Documents\\GitHub\\ReEDS-2.0\\inputs\\capacitydata\\ReEDS_generator_database_final_RTS-GMLC_updated_nodal.csv', sep=',', encoding='utf-8', index=False)